# Standards: 0.1
---
- name: Fact buttercup user
  set_fact:
    buttercup_user: "{{ buttercup_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - buttercup

- become: "{{ (buttercup_user != ansible_user_id) | bool }}"
  become_user: "{{ buttercup_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: buttercup
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - buttercup

- name: Remove quarantine flag
  register: buttercup_quarantine
  failed_when: buttercup_quarantine.rc != 0 and "No such xattr" not in buttercup_quarantine.stderr
  changed_when: buttercup_quarantine.rc == 0
  command: xattr -d com.apple.quarantine /Applications/Buttercup.app
  tags:
    - buttercup

...
